// Modal.jsx
import { useEffect, useState } from "react";
import "./Styles/modal.css";

const Modal = ({ open, onClose }) => {
  const [isVisible, setIsVisible] = useState(false);
  const [isClosing, setIsClosing] = useState(false);

  useEffect(() => {
    if (open) {
      setIsVisible(true);
      setIsClosing(false);
    } else if (isVisible) {
      setIsClosing(true);
      const timer = setTimeout(() => {
        setIsVisible(false);
        setIsClosing(false);
      }, 300); // matches fadeOutPop duration
      return () => clearTimeout(timer);
    }
  }, [open, isVisible]);

  if (!isVisible) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div
        className={`modal-content ${isClosing ? "hide" : ""}`}
        onClick={(e) => e.stopPropagation()}
      >
        <h2>
          Welcome to <strong>Music Taste!</strong>
        </h2>
        <p>
          Create a <strong>Karinderya Menu</strong> based on your unique{" "}
          <strong>music taste</strong>! Your menu is generated by analyzing your
          top artists and tracks from Spotify, Last.fm, or Apple Music.
        </p>
        <p>
          Open your <strong>Karinderya</strong> by linking your music account,
          and enjoy a menu that’s as flavorful as your playlist.
        </p>
        <p>
          Developed by{" "}
          <strong>
            👾<a href="#">Richard</a> & 🤖<a href="#">Sean</a>
          </strong>
          .
        </p>
        <p>
          Based on the app <a href="https://www.instafest.app/">Instafest</a> —
          go check it out too!
        </p>
        <p>
          For more information on how we handle your data, please refer to our{" "}
          <a href="#" target="_blank" rel="noopener noreferrer">
            Privacy Policy
          </a>
          .
        </p>
        <button onClick={onClose} className="modal-close-btn">
          Close
        </button>
      </div>
    </div>
  );
};

export default Modal;
