import { useState } from "react";
import "./App.css";
import Heading from "./Components/Heading";
import Body from "./Components/Body";
import Footer from "./Components/Footer";
import Modal from "./Components/Modal";

function App() {
  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <>
      <Heading openModal={() => setIsModalOpen(true)} />
      <Body />
      <Footer />

      {/* Global Modal */}
      <Modal open={isModalOpen} onClose={() => setIsModalOpen(false)}>
        <h2>
          Welcome to <strong>Music Taste!</strong>
        </h2>
        <p>
          Create a <strong>Karinderya Menu</strong> based on your unique{" "}
          <strong>music taste</strong>! Your menu is generated by analyzing your
          top artists and tracks from Spotify, Last.fm, or Apple Music.
        </p>
        <p>
          Open your <strong>Karinderya</strong> by linking your music account,
          and enjoy a menu that’s as flavorful as your playlist.
        </p>
        <p>
          Developed by{" "}
          <strong>
            👾<a href="">Richard</a> & 🤖<a href="">Sean</a>
          </strong>
          .
        </p>
        <p>
          Based on the app <a href="https://www.instafest.app/">Instafest</a> go
          check it out too!
        </p>
        <p>
          For more information on how we handle your data, please refer to our{" "}
          <a href="#" target="_blank" rel="noopener noreferrer">
            Privacy Policy
          </a>
          .
        </p>
        <button
          onClick={() => setIsModalOpen(false)}
          className="modal-close-btn"
        >
          Close
        </button>
      </Modal>
    </>
  );
}

export default App;
